-- Sample tools data for VaultX AI Tools
-- Run this in your Supabase SQL editor

-- Design Category Tools
INSERT INTO tools (id, name, logo, description, long_description, category, rating, review_count, weekly_users, growth, website, pricing, features, pros, cons, alternatives, tags, created_at, updated_at) VALUES
(gen_random_uuid(), 'Midjourney', '🎨', 'AI-powered image generation from text descriptions', 'Midjourney is a cutting-edge AI art generation tool that creates stunning images from text prompts. It''s known for its artistic quality and ability to generate highly detailed, creative visuals across various styles and genres.', 'Design', 4.6, 892, 12850, '+32%', 'https://midjourney.com', 'Paid', ARRAY['Text-to-image generation', 'High-resolution outputs', 'Multiple art styles', 'Customizable parameters', 'Community features', 'Discord integration'], ARRAY['Exceptional artistic quality', 'Wide range of styles', 'Active community', 'Regular model updates'], ARRAY['Requires Discord account', 'No free tier', 'Limited commercial usage', 'Queue times during peak hours'], '[{"name": "DALL-E", "rating": 4.6, "logo": "🖼️"}, {"name": "Stable Diffusion", "rating": 4.4, "logo": "🎭"}, {"name": "Canva AI", "rating": 4.3, "logo": "🎨"}]'::jsonb, ARRAY['AI Art', 'Image Generation', 'Design', 'Creative'], NOW(), NOW()),

(gen_random_uuid(), 'DALL-E', '🖼️', 'OpenAI''s AI image generation model', 'DALL-E is OpenAI''s advanced AI system that creates images from natural language descriptions. It can generate, edit, and create variations of images with remarkable creativity and detail.', 'Design', 4.5, 756, 10200, '+28%', 'https://openai.com/dall-e-2', 'Paid', ARRAY['Text-to-image generation', 'Image editing', 'Variations creation', 'High-quality outputs', 'Commercial usage rights'], ARRAY['High-quality outputs', 'Commercial usage', 'Easy to use', 'Regular updates'], ARRAY['Limited free tier', 'Can be expensive', 'Content restrictions', 'Queue times'], '[{"name": "Midjourney", "rating": 4.6, "logo": "🎨"}, {"name": "Stable Diffusion", "rating": 4.4, "logo": "🎭"}, {"name": "Canva AI", "rating": 4.3, "logo": "🎨"}]'::jsonb, ARRAY['AI Art', 'Image Generation', 'OpenAI', 'Creative'], NOW(), NOW()),

(gen_random_uuid(), 'Canva AI', '🎨', 'AI-powered design tool for everyone', 'Canva AI integrates artificial intelligence into the popular design platform, making it easier for anyone to create professional graphics, presentations, and visual content.', 'Design', 4.3, 1243, 15600, '+45%', 'https://canva.com', 'Freemium', ARRAY['AI-powered design suggestions', 'Template library', 'Collaboration tools', 'Brand kit management', 'Video editing', 'Social media templates'], ARRAY['User-friendly interface', 'Extensive template library', 'Free tier available', 'Great for beginners'], ARRAY['Limited advanced features', 'Watermark on free version', 'Internet required', 'Can be slow with large files'], '[{"name": "Figma", "rating": 4.4, "logo": "🎯"}, {"name": "Adobe Creative Suite", "rating": 4.7, "logo": "🎨"}, {"name": "Crello", "rating": 4.2, "logo": "🎭"}]'::jsonb, ARRAY['Design', 'Templates', 'Collaboration', 'Social Media'], NOW(), NOW());

-- Language Category Tools
INSERT INTO tools (id, name, logo, description, long_description, category, rating, review_count, weekly_users, growth, website, pricing, features, pros, cons, alternatives, tags, created_at, updated_at) VALUES
(gen_random_uuid(), 'ChatGPT', '🤖', 'Advanced language model for conversation and text generation', 'ChatGPT is an AI-powered conversational agent that can engage in natural language conversations, answer questions, provide explanations, and assist with various tasks. It''s built on OpenAI''s GPT architecture and can understand context, generate human-like responses, and adapt to different conversation styles.', 'Language', 4.8, 1247, 15420, '+45%', 'https://chat.openai.com', 'Freemium', ARRAY['Natural language conversations', 'Context-aware responses', 'Multi-language support', 'Code generation and debugging', 'Creative writing assistance', 'Educational explanations', 'Real-time responses', 'Customizable conversation styles'], ARRAY['Highly accurate and contextual responses', 'Excellent for learning and education', 'Free tier available', 'Regular updates and improvements', 'Good for creative tasks'], ARRAY['Can sometimes provide incorrect information', 'Limited to training data cutoff', 'May not always understand complex queries', 'Privacy concerns with data handling'], '[{"name": "Claude", "rating": 4.7, "logo": "🧠"}, {"name": "Bard", "rating": 4.5, "logo": "🤖"}, {"name": "Perplexity", "rating": 4.6, "logo": "🔍"}]'::jsonb, ARRAY['AI', 'Language', 'Conversation', 'OpenAI'], NOW(), NOW()),

(gen_random_uuid(), 'Claude', '🧠', 'Anthropic''s AI assistant for complex reasoning', 'Claude is an AI assistant developed by Anthropic, designed to be helpful, harmless, and honest. It excels at complex reasoning tasks, writing, analysis, and coding.', 'Language', 4.7, 892, 8900, '+38%', 'https://claude.ai', 'Paid', ARRAY['Complex reasoning', 'Code generation', 'Writing assistance', 'Analysis capabilities', 'Safety-focused design', 'Long context window'], ARRAY['Excellent reasoning capabilities', 'Safety-focused', 'Good for complex tasks', 'Reliable responses'], ARRAY['Limited free access', 'Can be expensive', 'Slower than some alternatives', 'Limited image capabilities'], '[{"name": "ChatGPT", "rating": 4.8, "logo": "🤖"}, {"name": "Bard", "rating": 4.5, "logo": "🤖"}, {"name": "Perplexity", "rating": 4.6, "logo": "🔍"}]'::jsonb, ARRAY['AI', 'Reasoning', 'Writing', 'Anthropic'], NOW(), NOW()),

(gen_random_uuid(), 'Grammarly', '✍️', 'AI-powered writing assistant', 'Grammarly is an AI-powered writing assistant that helps improve grammar, spelling, punctuation, clarity, and tone. It works across multiple platforms and provides real-time suggestions.', 'Language', 4.4, 2156, 18200, '+25%', 'https://grammarly.com', 'Freemium', ARRAY['Grammar checking', 'Spell checking', 'Tone analysis', 'Plagiarism detection', 'Writing suggestions', 'Multi-platform support'], ARRAY['Comprehensive grammar checking', 'Easy to use', 'Works across platforms', 'Good free tier'], ARRAY['Can be overly aggressive', 'Premium features expensive', 'Privacy concerns', 'Not always accurate'], '[{"name": "ProWritingAid", "rating": 4.3, "logo": "📝"}, {"name": "Hemingway Editor", "rating": 4.2, "logo": "✍️"}, {"name": "LanguageTool", "rating": 4.1, "logo": "🔧"}]'::jsonb, ARRAY['Writing', 'Grammar', 'Spelling', 'Productivity'], NOW(), NOW());

-- Development Category Tools
INSERT INTO tools (id, name, logo, description, long_description, category, rating, review_count, weekly_users, growth, website, pricing, features, pros, cons, alternatives, tags, created_at, updated_at) VALUES
(gen_random_uuid(), 'GitHub Copilot', '💻', 'AI pair programmer that helps write code faster', 'GitHub Copilot is an AI-powered code completion tool that suggests whole lines or blocks of code as you type. It''s trained on billions of lines of code and can help developers write code faster and with fewer errors.', 'Development', 4.6, 1345, 12300, '+52%', 'https://github.com/features/copilot', 'Paid', ARRAY['Code completion', 'Multi-language support', 'IDE integration', 'Context-aware suggestions', 'Code explanation', 'Test generation'], ARRAY['Excellent code suggestions', 'Multi-language support', 'Seamless IDE integration', 'Saves development time'], ARRAY['Can suggest incorrect code', 'Privacy concerns', 'Expensive for individuals', 'Requires internet connection'], '[{"name": "Cursor", "rating": 4.5, "logo": "⌨️"}, {"name": "Tabnine", "rating": 4.3, "logo": "🤖"}, {"name": "CodeWhisperer", "rating": 4.4, "logo": "💡"}]'::jsonb, ARRAY['Coding', 'AI Assistant', 'Productivity', 'GitHub'], NOW(), NOW()),

(gen_random_uuid(), 'Cursor', '⌨️', 'AI-first code editor built for developers', 'Cursor is a modern code editor built with AI at its core. It combines the power of VS Code with advanced AI capabilities to help developers write, understand, and debug code more efficiently.', 'Development', 4.5, 678, 5600, '+67%', 'https://cursor.sh', 'Freemium', ARRAY['AI code completion', 'Chat with codebase', 'Code explanation', 'Bug fixing', 'Refactoring assistance', 'VS Code compatibility'], ARRAY['Excellent AI integration', 'VS Code compatible', 'Free tier available', 'Active development'], ARRAY['Newer tool', 'Limited community', 'Some features experimental', 'Can be resource-intensive'], '[{"name": "GitHub Copilot", "rating": 4.6, "logo": "💻"}, {"name": "Tabnine", "rating": 4.3, "logo": "🤖"}, {"name": "CodeWhisperer", "rating": 4.4, "logo": "💡"}]'::jsonb, ARRAY['Code Editor', 'AI', 'Development', 'Productivity'], NOW(), NOW()),

(gen_random_uuid(), 'Tabnine', '🤖', 'AI code completion for all languages', 'Tabnine is an AI-powered code completion tool that works with any programming language and IDE. It learns from your codebase to provide personalized suggestions.', 'Development', 4.3, 892, 7800, '+34%', 'https://tabnine.com', 'Freemium', ARRAY['Multi-language support', 'IDE integration', 'Local model option', 'Team learning', 'Custom models', 'Privacy-focused'], ARRAY['Works with any language', 'Privacy-focused options', 'Good free tier', 'Team learning capabilities'], ARRAY['Less accurate than some alternatives', 'Slower suggestions', 'Limited advanced features', 'Complex setup'], '[{"name": "GitHub Copilot", "rating": 4.6, "logo": "💻"}, {"name": "Cursor", "rating": 4.5, "logo": "⌨️"}, {"name": "CodeWhisperer", "rating": 4.4, "logo": "💡"}]'::jsonb, ARRAY['Code Completion', 'AI', 'Development', 'Multi-language'], NOW(), NOW());

-- Marketing Category Tools
INSERT INTO tools (id, name, logo, description, long_description, category, rating, review_count, weekly_users, growth, website, pricing, features, pros, cons, alternatives, tags, created_at, updated_at) VALUES
(gen_random_uuid(), 'Jasper', '📝', 'AI content creation platform for marketing', 'Jasper is an AI-powered content creation platform designed specifically for marketers. It helps create high-quality content for blogs, social media, ads, and more.', 'Marketing', 4.4, 1156, 9800, '+41%', 'https://jasper.ai', 'Paid', ARRAY['Content generation', 'SEO optimization', 'Brand voice training', 'Multi-language support', 'Team collaboration', 'Content templates'], ARRAY['Excellent for marketing content', 'Good brand voice training', 'SEO optimization', 'Team features'], ARRAY['Expensive', 'Can be repetitive', 'Limited customization', 'Requires human editing'], '[{"name": "Copy.ai", "rating": 4.3, "logo": "✍️"}, {"name": "Writesonic", "rating": 4.2, "logo": "📄"}, {"name": "Surfer SEO", "rating": 4.5, "logo": "📊"}]'::jsonb, ARRAY['Content Creation', 'Marketing', 'SEO', 'AI Writing'], NOW(), NOW()),

(gen_random_uuid(), 'Copy.ai', '✍️', 'AI copywriting tool for businesses', 'Copy.ai is an AI-powered copywriting tool that helps businesses create compelling marketing copy, product descriptions, and content that converts.', 'Marketing', 4.3, 987, 8200, '+38%', 'https://copy.ai', 'Freemium', ARRAY['Copy generation', 'Product descriptions', 'Social media content', 'Email marketing', 'Landing page copy', 'Brand voice training'], ARRAY['Good for marketing copy', 'Easy to use', 'Free tier available', 'Multiple content types'], ARRAY['Can be generic', 'Limited customization', 'Requires editing', 'Not always brand-appropriate'], '[{"name": "Jasper", "rating": 4.4, "logo": "📝"}, {"name": "Writesonic", "rating": 4.2, "logo": "📄"}, {"name": "Phrasee", "rating": 4.1, "logo": "🎯"}]'::jsonb, ARRAY['Copywriting', 'Marketing', 'Content', 'AI'], NOW(), NOW()),

(gen_random_uuid(), 'Surfer SEO', '📊', 'AI-powered SEO optimization tool', 'Surfer SEO is an AI-powered tool that helps optimize content for search engines. It provides keyword research, content optimization suggestions, and competitive analysis.', 'Marketing', 4.5, 756, 6500, '+29%', 'https://surferseo.com', 'Paid', ARRAY['Keyword research', 'Content optimization', 'Competitive analysis', 'SERP analysis', 'Content editor', 'Site audit'], ARRAY['Excellent SEO insights', 'Data-driven recommendations', 'Comprehensive analysis', 'User-friendly interface'], ARRAY['Expensive', 'Steep learning curve', 'Limited free trial', 'Requires technical knowledge'], '[{"name": "Ahrefs", "rating": 4.6, "logo": "📈"}, {"name": "SEMrush", "rating": 4.4, "logo": "🔍"}, {"name": "Moz", "rating": 4.3, "logo": "📊"}]'::jsonb, ARRAY['SEO', 'Marketing', 'Analytics', 'Content Optimization'], NOW(), NOW());

-- Productivity Category Tools
INSERT INTO tools (id, name, logo, description, long_description, category, rating, review_count, weekly_users, growth, website, pricing, features, pros, cons, alternatives, tags, created_at, updated_at) VALUES
(gen_random_uuid(), 'Notion AI', '📝', 'AI assistant integrated into Notion workspace', 'Notion AI brings artificial intelligence directly into your Notion workspace, helping you write, brainstorm, edit, and organize your work more efficiently.', 'Productivity', 4.4, 1345, 11200, '+48%', 'https://notion.so', 'Freemium', ARRAY['AI writing assistance', 'Brainstorming', 'Content editing', 'Task automation', 'Knowledge organization', 'Team collaboration'], ARRAY['Seamless integration', 'Excellent for organization', 'Team collaboration', 'Flexible workspace'], ARRAY['Can be overwhelming', 'Steep learning curve', 'Limited AI features', 'Expensive for teams'], '[{"name": "Obsidian", "rating": 4.3, "logo": "💎"}, {"name": "Roam Research", "rating": 4.2, "logo": "🧠"}, {"name": "Logseq", "rating": 4.1, "logo": "📚"}]'::jsonb, ARRAY['Productivity', 'Organization', 'Collaboration', 'AI Writing'], NOW(), NOW()),

(gen_random_uuid(), 'Otter.ai', '🎙️', 'AI-powered meeting transcription and notes', 'Otter.ai uses AI to transcribe meetings, generate notes, and help teams collaborate more effectively. It works with video conferencing platforms and provides real-time transcription.', 'Productivity', 4.3, 892, 7800, '+35%', 'https://otter.ai', 'Freemium', ARRAY['Meeting transcription', 'Real-time notes', 'Speaker identification', 'Video conferencing integration', 'Search and sharing', 'Team collaboration'], ARRAY['Accurate transcription', 'Real-time capabilities', 'Good integration', 'Easy to use'], ARRAY['Limited free tier', 'Can be expensive', 'Privacy concerns', 'Not always accurate'], '[{"name": "Fireflies", "rating": 4.4, "logo": "🦗"}, {"name": "Rev", "rating": 4.2, "logo": "📝"}, {"name": "Descript", "rating": 4.3, "logo": "🎬"}]'::jsonb, ARRAY['Transcription', 'Meetings', 'Productivity', 'AI'], NOW(), NOW()),

(gen_random_uuid(), 'Fireflies', '🦗', 'AI meeting assistant and transcription', 'Fireflies is an AI meeting assistant that joins your calls, takes notes, and helps you stay focused on the conversation while it handles the documentation.', 'Productivity', 4.4, 756, 6800, '+42%', 'https://fireflies.ai', 'Freemium', ARRAY['Meeting recording', 'AI transcription', 'Action item tracking', 'Meeting insights', 'CRM integration', 'Team collaboration'], ARRAY['Excellent meeting insights', 'Good integrations', 'Action item tracking', 'Easy setup'], ARRAY['Privacy concerns', 'Limited free tier', 'Can be expensive', 'Requires meeting access'], '[{"name": "Otter.ai", "rating": 4.3, "logo": "🎙️"}, {"name": "Rev", "rating": 4.2, "logo": "📝"}, {"name": "Descript", "rating": 4.3, "logo": "🎬"}]'::jsonb, ARRAY['Meetings', 'Transcription', 'Productivity', 'AI Assistant'], NOW(), NOW()); 